### ISSUE TITLE
Compilation error when enabling Microsoft.Extensions.ApiDescription.Server after migrating demo code to my own project

### ISSUE THREAD

**Issue by neozhu** [tpeczek/Demo.AspNetCore.PushNotifications#21]
Hello, I encountered an issue when migrating your demo code into my own project. If I enable Microsoft.Extensions.ApiDescription.Server, I get compilation errors. However, removing Microsoft.Extensions.ApiDescription.Server stops the errors but then openapi.json is not generated.

I’ve also tried upgrading your demo to .NET 9, but the problem persists. I’m not sure what’s causing the issue, so I’m hoping you can take a look.

Thank you very much for providing this example project. I’m looking forward to using it in my Blazor Assembly PWA project to implement push notifications, and your work has been really helpful.

Looking forward to your guidance!
```
14>  dotnet "C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\../tools/dotnet-getdocument.dll" --assembly "D:\github\CleanAspire\src\CleanAspire.Api\bin\Debug\net9.0\CleanAspire.Api.dll" --file-list "obj\CleanAspire.Api.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v9.0" --output "D:\github\CleanAspire\src\CleanAspire.Api" --project "CleanAspire.Api" --assets-file "D:\github\CleanAspire\src\CleanAspire.Api\obj\project.assets.json" --platform "AnyCPU"
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error : System.AggregateException: One or more errors occurred. (The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :  ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Convert.FromBase64String(String s)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Internals.UrlBase64Converter.FromUrlBase64String(String input) in /_/src/Lib.Net.Http.WebPush/Internals/UrlBase64Converter.cs:line 16
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Authentication.VapidAuthentication.set_PublicKey(String value) in /_/src/Lib.Net.Http.WebPush/Authentication/VapidAuthentication.cs:line 109
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Authentication.VapidAuthentication..ctor(String publicKey, String privateKey) in /_/src/Lib.Net.Http.WebPush/Authentication/VapidAuthentication.cs:line 177
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.PushServiceClientServiceCollectionExtensions.<>c.<AddPushServiceClient>b__4_0(IServiceProvider serviceProvider) in /_/src/Lib.AspNetCore.WebPush/PushServiceClientServiceCollectionExtensions.cs:line 80
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.PushServiceClientServiceCollectionExtensions.<>c.<AddPushServiceClient>b__4_1(IServiceProvider serviceProvider) in /_/src/Lib.AspNetCore.WebPush/PushServiceClientServiceCollectionExtensions.cs:line 107
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Program.<Main>$(String[] args) in D:\github\CleanAspire\src\CleanAspire.Api\Program.cs:line 135
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Program.<Main>(String[] args)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    --- End of inner exception stack trace ---
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at System.Threading.Tasks.Task.Wait()
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.Process()
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error MSB3073: The command "dotnet "C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\../tools/dotnet-getdocument.dll" --assembly "D:\github\CleanAspire\src\CleanAspire.Api\bin\Debug\net9.0\CleanAspire.Api.dll" --file-list "obj\CleanAspire.Api.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v9.0" --output "D:\github\CleanAspire\src\CleanAspire.Api" --project "CleanAspire.Api" --assets-file "D:\github\CleanAspire\src\CleanAspire.Api\obj\project.assets.json" --platform "AnyCPU" " exited with code 11.
14>Done building project "CleanAspire.Api.csproj" -- FAILED.
```

![image](https://github.com/user-attachments/assets/73ddc977-31b4-41be-b839-566245d17d71)

**Comment by tpeczek** [comment]
Hi @neozhu,

This is not a compilation error, this is a runtime issue due to misconfiguration.

The `Microsoft.Extensions.ApiDescription.Server` attempts to execute the pipeline during build to obtain information needed to generate documentation. Here it fails due to VAPID keys missing in configuration:

```
...
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Internals.UrlBase64Converter.FromUrlBase64String(String input) in /_/src/Lib.Net.Http.WebPush/Internals/UrlBase64Converter.cs:line 16
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Authentication.VapidAuthentication.set_PublicKey(String value) in /_/src/Lib.Net.Http.WebPush/Authentication/VapidAuthentication.cs:line 109
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Lib.Net.Http.WebPush.Authentication.VapidAuthentication..ctor(String publicKey, String privateKey) in /_/src/Lib.Net.Http.WebPush/Authentication/VapidAuthentication.cs:line 177
14>C:\Users\neo_z\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets(68,5): error :    at Microsoft.Extensions.DependencyInjection.PushServiceClientServiceCollectionExtensions.<>c.<AddPushServiceClient>b__4_0(IServiceProvider serviceProvider) in /_/src/Lib.AspNetCore.WebPush/PushServiceClientServiceCollectionExtensions.cs:line 80
...
```

Now, I'm assuming that you have simply copied `PushServiceServiceCollectionExtensions` from the demo app. In the demo it implements the simplest approach, reading keys at startup:

```cs
public static IServiceCollection AddPushServicePushNotificationService(this IServiceCollection services, IConfiguration configuration)
{
    services.AddMemoryCache();
    services.AddMemoryVapidTokenCache();
    services.AddPushServiceClient(options =>
    {
        IConfigurationSection pushNotificationServiceConfigurationSection = configuration.GetSection(nameof(PushServiceClient));

        options.Subject = pushNotificationServiceConfigurationSection.GetValue<string>(nameof(options.Subject));
        options.PublicKey = pushNotificationServiceConfigurationSection.GetValue<string>(nameof(options.PublicKey));
        options.PrivateKey = pushNotificationServiceConfigurationSection.GetValue<string>(nameof(options.PrivateKey));
    });
    services.AddTransient<IPushNotificationService, PushServicePushNotificationService>();

    return services;
}
```

You have two options. You can either ensure that `appsettings.json` with provided keys is available in the context where `Microsoft.Extensions.ApiDescription.Server` attempts to run the pipeline, or you can modify the initialisation code so the configuration read is deffered and performed only when needed.

**Comment by neozhu** [comment]
Thank you for responding so quickly; it was very helpful.
